defaults:
  - _self_
  - gen_model: large_maf
  - disc_model: mlp

hydra:
  sweeper:
    max_batch_size: 1

neptune:
  enable: false
  project: "ofurman/GWCE"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["WACH"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

disc_model:
  train_model: false
  epochs: 5000
  batch_size: 128
  patience: 300
  lr: 0.001
  noise_lvl: 0.00

gen_model:
  train_model: false
  batch_size: 128
  epochs: 2000
  patience: 100
  lr: 0.001
  noise_lvl: 0.02

counterfactuals_params:
  cf_method:
    # specific parameters besides standard ones should be passed here
    _target_: counterfactuals.cf_methods.artelt_gw.artelt_gw.ArteltGW

  log_prob_quantile: 0.25
  origin_class: 0
  target_class: 1
  batch_size: 8192
  # epochs: 20000
  # lr: 0.001
  # alpha: 1000
  # alpha_s: 1000
  # alpha_k: 100
  # beta: 0.01
  # patience: 1000
  
    
