defaults:
  - _self_
  - gen_model: large_maf
  - disc_model: mlp

hydra:
  sweeper:
    max_batch_size: 1

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["GenCE"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.HelocDataset

disc_model:
  train_model: false
  epochs: 5000
  batch_size: 128
  patience: 300
  lr: 0.001

gen_model:
  train_model: true
  batch_size: 1024
  epochs: 2000
  patience: 100
  lr: 0.003
  noise_lvl: 0.03

counterfactuals_params:
  cf_method:
    # specific parameters besides standard ones should be passed here
    _target_: counterfactuals.cf_methods.GenCE

  log_prob_quantile: 0.25
  target_class: 0
  epochs: 20000
  batch_size: 4096
  lr: 0.001
  patience: 1000
  
    
