defaults:
  - _self_
  - gen_model: large_maf
  - disc_model: mlp

hydra:
  sweeper:
    max_batch_size: 1

neptune:
  enable: false
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["GLOBE_CE", "counterfactuals"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

disc_model:
  train_model: true
  epochs: 5000
  batch_size: 128
  patience: 300
  lr: 0.001

gen_model:
  train_model: true
  batch_size: 1024
  epochs: 2000
  patience: 50
  lr: 0.003
  noise_lvl: 0.02

counterfactuals_params:
  cf_method:
    _target_: counterfactuals.cf_methods.globe_ce.GLOBE_CE
  
  # General parameters
  target_class: 0
  batch_size: 4096
  log_prob_quantile: 0.25
