defaults:
  - _self_
  - gen_model: large_maf
  - disc_model: mlr

hydra:
  sweeper:
    max_batch_size: 1

neptune:
  enable: false
  project: "ofurman/GWCE"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["GCE"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

disc_model:
  train_model: true
  epochs: 5000
  batch_size: 128
  patience: 300
  lr: 0.001
  noise_lvl: 0.00

gen_model:
  train_model: true
  batch_size: 128
  epochs: 2000
  patience: 100
  lr: 0.001
  noise_lvl: 0.02

counterfactuals_params:
  cf_method:
    # specific parameters besides standard ones should be passed here
    _target_: counterfactuals.cf_methods.RPPCEF
    cf_method_type: "GCE"
    K: null

  disc_model_criterion:
    _target_: counterfactuals.losses.MulticlassDiscLoss
    eps: 0.01
    # _target_: counterfactuals.losses.BinaryDiscLoss

  log_prob_quantile: 0.25
  origin_class: 0
  target_class: 1
  epochs: 50_000
  batch_size: 8096
  lr: 0.01
  patience: 500
  decrease_loss_patience: 1_000
  alpha_dist: 0.1
  alpha_plaus: 10_000
  alpha_class: 100_000
  alpha_s: 1_000
  alpha_k: 10_000
  alpha_d: 100
