defaults:
  - _self_
  - gen_model: large_maf
  - disc_model: mlp

hydra:
  sweeper:
    max_batch_size: 1

neptune:
  enable: false
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["19.05", "GCE", "no_plausability", "Q1_log_prob_threshold", "all_methods", "lambda_ablation"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.BlobsDataset

disc_model:
  train_model: true
  epochs: 5000
  batch_size: 128
  patience: 300
  lr: 0.001

gen_model:
  train_model: true
  batch_size: 1024
  epochs: 2000
  patience: 100
  lr: 0.003
  noise_lvl: 0.02

counterfactuals_params:
  cf_method:
    # specific parameters besides standard ones should be passed here
    _target_: counterfactuals.cf_methods.RPPCEF
    cf_method_type: "PPCEF_2"
    K: 1

  disc_model_criterion:
    _target_: counterfactuals.losses.MulticlassDiscLoss
    # _target_: counterfactuals.losses.BinaryDiscLoss

  log_prob_quantile: 0.25
  target_class: 0
  epochs: 20000
  batch_size: 4096
  lr: 0.001
  alpha: 1000
  alpha_s: 1000
  alpha_k: 100
  beta: 0.01
  patience: 1000
  
    
