model:
  _target_: counterfactuals.models.generative.CeFlowGMM
  n_classes: 2
  hidden_features: 64
  num_layers: 5
  num_blocks_per_layer: 2
  dequant_hidden_dim: 32
  gmm_init_std: 1.0
  learn_gmm_covariance: true
  dropout_probability: 0.0
  batch_norm_within_layers: false
