defaults:
  - _self_
  - gen_model: small_flow

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["run_exp", "GEN_DISC_LOSS"]
  

experiment:
  output_folder: output/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

gen_model:
  checkpoint_path: null
  batch_size: 128
  epochs: 200
  patience: 20

disc_model: "lr" # "mlp"

counterfactuals:
  epochs: 1000
  batch_size: 16
  lr: 0.005
  alpha: 20
  beta: 0.1