defaults:
  - _self_
  - gen_model: medium_maf
  - disc_model: mlp

hydra:
  sweeper:
    max_batch_size: 1

neptune:
  enable: false
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["exp_v1", "GEN_DISC_LOSS"]

experiment:
  output_folder: models/
  relabel_with_disc_model: false

dataset:
  _target_: counterfactuals.datasets.LawDataset

disc_model:
  epochs: 300
  batch_size: 512
  patience: 300
  lr: 0.003

gen_model:
  batch_size: 512
  epochs: 2000
  patience: 50
  lr: 0.001
  noise_lvl: 0.02

counterfactuals:
  epochs: 2000
  batch_size: 4096
  lr: 0.005
  alpha: 100
  beta: 0.01
  patience: 500
  disc_loss:
    _target_: counterfactuals.losses.MulticlassDiscLoss
    # _target_: counterfactuals.losses.BinaryDiscLoss