defaults:
  - _self_
  - gen_model: small_flow

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["train_models"]
  

experiment:
  output_folder: models/

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

gen_model:
  model: KDE
  checkpoint_path: null
  batch_size: 128
  epochs: 200
  patience: 20
  lr: 0.001
  noise_lvl: 0

disc_model:
  model: null # LR, MLP, null