defaults:
  - _self_

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: false
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["exp_v1", "GEN_DISC_LOSS"]

experiment:
  output_folder: models/
  relabel_with_disc_model: false


dataset_name: 'german_credit'
model_path: './counterfactuals/global_cfs_utils/models'

model: lr

counterfactuals:
  epochs: 5000
  batch_size: 2048
  lr: 0.005
  alpha: 100
  beta: 0.01
  patience: 500
  disc_loss:
    _target_: counterfactuals.losses.BinaryDiscLoss
    # _target_: torch.nn.BCEWithLogitsLoss