defaults:
  - _self_
  - gen_model: small_flow

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["development"]
  

experiment:
  output_folder: output/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.LawDataset

gen_model:
  checkpoint_path: null
  batch_size: 128
  epochs: 200
  patience: 20

disc_model:
  # _target_: "sklearn.linear_model.LogisticRegression"
  _target_: sklearn.neural_network.MLPClassifier

counterfactuals:
  epochs: 200
  batch_size: 128
  lr: 0.005
  alpha: 10
  beta: 0.01