defaults:
  - _self_
  - disc_model: lr

model: lr

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["ares", "heloc", "lr"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true


dataset:
  _target_: counterfactuals.datasets.HelocDataset
  # _target_: counterfactuals.datasets.AuditDataset


counterfactuals:
  epochs: 5000
  batch_size: 2048
  lr: 0.005
  alpha: 100
  beta: 0.01
  patience: 500
  disc_loss:
    _target_: counterfactuals.losses.BinaryDiscLoss
    # _target_: torch.nn.BCEWithLogitsLoss

disc_model:
  epochs: 5000
  batch_size: 64
  patience: 300
  lr: 0.001
