defaults:
  - _self_
  - gen_model: small_flow

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["run_exp", "GEN_DISC_LOSS"]
  

experiment:
  models_folder: models/
  relabel_with_disc_model: false

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

disc_model:
  model: DTC # LR, MLP, 

counterfactuals:
  epochs: 2000
  batch_size: 16
  lr: 0.005
  alpha: 1000
  beta: 0.01
  disc_loss:
    # _target_: counterfactuals.losses.BinaryDiscLoss
    _target_: torch.nn.BCEWithLogitsLoss