defaults:
  - _self_
  - gen_model: small_flow

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["exp_v1", "GEN_DISC_LOSS"]
  

experiment:
  models_folder: models/
  relabel_with_disc_model: false

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

disc_model:
  model: LR

gen_model:
  model: FLOW

counterfactuals:
  epochs: 5000
  batch_size: 2048
  lr: 0.005
  alpha: 100
  beta: 0.01
  patience: 100
  disc_loss:
    _target_: counterfactuals.losses.BinaryDiscLoss
    # _target_: torch.nn.BCEWithLogitsLoss