defaults:
  - _self_
  - gen_model: medium_maf
  - disc_model: lr

hydra:
  sweeper:
    max_batch_size: 1

neptune:
  enable: false
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["exp_v8", "GLOBAL_PPCEF", "plausability", "OUR", "k_ablation"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.HelocDataset
  # _target_: counterfactuals.datasets.GermanCreditDataset

disc_model:
  epochs: 5000
  batch_size: 64
  patience: 300
  lr: 0.001

gen_model:
  batch_size: 1024
  epochs: 2000
  patience: 70
  lr: 0.003
  noise_lvl: 0.02

counterfactuals:
  K: 5
  origin_class: 0
  epochs: 20000
  batch_size: 4096
  lr: 0.003
  alpha: 100
  beta: 0.01
  patience: 500
  disc_loss:
    # _target_: counterfactuals.losses.MulticlassDiscLoss
    _target_: counterfactuals.losses.BinaryDiscLoss

method: null