defaults:
  - _self_
  - disc_model: mlp

model: mlp

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["GLOBE_CE", "german_credit", "MLP", "relabeling"]

experiment:
  output_folder: models/
  relabel_with_disc_model: true


dataset:
  _target_: counterfactuals.datasets.GermanCreditDataset
  # _target_: counterfactuals.datasets.HelocDataset


counterfactuals:
  epochs: 5000
  batch_size: 2048
  lr: 0.005
  alpha: 100
  beta: 0.01
  patience: 500
  disc_loss:
    _target_: counterfactuals.losses.BinaryDiscLoss
    # _target_: torch.nn.BCEWithLogitsLoss