metrics_to_compute:
  - "coverage"
  - "validity"
  - "actionability"
  - "sparsity"
  - "proximity_euclidean_hamming"
  - "proximity_euclidean_jaccard"
  - "proximity_l1_jaccard"
  - "proximity_mad_jaccard"
  - "proximity_l2_jaccard"
  - "proximity_mad_hamming"
  - "prob_plausibility"
  - "log_density_cf"
  - "log_density_test"
  - "lof_scores_cf"
  - "lof_scores_test"
  - "isolation_forest_scores_cf"
  - "isolation_forest_scores_test"
