defaults:
  - _self_
  - gen_model: small_flow

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["ARTELTH20", "other_methods"]
  

experiment:
  output_folder: output/
  relabel_with_disc_model: false
  models_folder: models/

dataset:
  _target_: counterfactuals.datasets.MoonsDataset

disc_model: 
  model: LR # MLP

reference_method: "artelth20"
pca_dim: 10

gen_model:
  model: FLOW
  checkpoint_path: null
  batch_size: 128
  epochs: 200
  patience: 20