defaults:
  - _self_
  - gen_model: medium_maf
  - disc_model: mlr

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["CEGP", "other_methods"]
  

experiment:
  output_folder: models/
  relabel_with_disc_model: false

dataset:
  _target_: counterfactuals.datasets.AuditDataset

reference_method: "CEGP"
pca_dim: 25

counterfactuals:
  epochs: 1000
  batch_size: 2048

# gen_model:
#   batch_size: 256
#   epochs: 500
#   patience: 20
#   lr: 0.001
#   noise_lvl: 0