defaults:
  - _self_

hydra:
  sweeper:
    max_batch_size: 10

neptune:
  enable: true
  project: "ofurman/counterfactuals"
  api_token: ${oc.env:NEPTUNE_API_TOKEN}
  tags: ["WACH", "other_methods"]
  

experiment:
  output_folder: output/
  relabel_with_disc_model: true

dataset:
  _target_: counterfactuals.datasets.LawDataset

disc_model:
  # _target_: "sklearn.linear_model.LogisticRegression"
  _target_: sklearn.neural_network.MLPClassifier
